# Generated by Django 5.1.5 on 2025-01-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.URLField(max_length=1000)),
                ('image', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
    ]
