# Generated by Django 5.1.5 on 2025-01-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='slide_index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
