# Generated by Django 5.1.5 on 2025-01-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destination', '0002_destination_slide_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
