# Generated by Django 5.1.5 on 2025-01-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destination', '0003_destination_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.URLField(max_length=250),
        ),
    ]
