# Generated by Django 5.1.5 on 2025-01-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destination', '0007_alter_destination_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(max_length=250, upload_to=''),
        ),
    ]
