# Generated by Django 5.1.5 on 2025-01-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destination', '0008_alter_destination_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.CharField(max_length=250),
        ),
    ]
